name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-deploy-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t my-nginx-cv -f Dockerfile .

      - name: Run container
        run: docker run -d -p 8080:80 --name my-nginx-container my-nginx-cv

      - name: Sleep to wait for container startup
        run: sleep 5

      - name: Test application response
        run: curl --fail http://localhost:8080 | grep "html"

