name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-deploy-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t my-nginx-cv .

    - name: Run container
      run: docker run -d -p 8080:80 --name cv-app my-nginx-cv

    - name: Sleep for 5 seconds
      run: sleep 5

    - name: Test application response
      run: curl -s http://localhost:8080 | grep "<html>"

